const ORTHOGRAPHIC_BASIS = 500
const AVERAGE_HUMAN_HEIGHT = 1.6

const CAMERAS_CONFIG_DEFAULTS = {
    ORTHOGRAPHIC_FRUSTUM_TOP: ORTHOGRAPHIC_BASIS,
    ORTHOGRAPHIC_FRUSTUM_BOTTOM: -ORTHOGRAPHIC_BASIS,
    ORTHOGRAPHIC_FRUSTUM_LEFT: -ORTHOGRAPHIC_BASIS * window.innerWidth / window.innerHeight,
    ORTHOGRAPHIC_FRUSTUM_RIGHT:  ORTHOGRAPHIC_BASIS * window.innerWidth / window.innerHeight,
    ORTHOGRAPHIC_FRUSTUM_NEAR: 0,
    ORTHOGRAPHIC_FRUSTUM_FAR: 100,
    PERSPECTIVE_ASPECT_RATIO: window.innerWidth / window.innerHeight,
    PERSPECTIVE_FOV: 70,
    PERSPECTIVE_FRUSTUM_FAR: 100,
    PERSPECTIVE_FRUSTUM_NEAR: 0.01,
    INITIAL_ORTHOGRAPHIC_POSITION: [0, 0, 0],
    INITIAL_ORTHOGRAPHIC_TARGET: [1, 0, 0],
    INITIAL_PERSPECTIVE_POSITION: [0, AVERAGE_HUMAN_HEIGHT, 0],
    INITIAL_PERSPECTIVE_TARGET: [1, AVERAGE_HUMAN_HEIGHT, 0],
}

module.exports = CAMERAS_CONFIG_DEFAULTS
