const ORTHOGRAPHIC_BASIS = 500
const AVERAGE_HUMAN_HEIGHT = 1.6

export interface CamerasConfig {
    ORTHOGRAPHIC_FRUSTUM_TOP: number,
    ORTHOGRAPHIC_FRUSTUM_BOTTOM: number,
    ORTHOGRAPHIC_FRUSTUM_LEFT: number,
    ORTHOGRAPHIC_FRUSTUM_RIGHT: number,
    ORTHOGRAPHIC_FRUSTUM_NEAR: number,
    ORTHOGRAPHIC_FRUSTUM_FAR: number,
    PERSPECTIVE_ASPECT_RATIO: number,
    PERSPECTIVE_FOV: number,
    PERSPECTIVE_FRUSTUM_FAR: number,
    PERSPECTIVE_FRUSTUM_NEAR: number,
    INITIAL_ORTHOGRAPHIC_POSITION: [ number, number, number ],
    INITIAL_ORTHOGRAPHIC_TARGET: [ number, number, number ],
    INITIAL_PERSPECTIVE_POSITION: [ number, number, number ],
    INITIAL_PERSPECTIVE_TARGET: [ number, number, number ],
}

const CAMERAS_CONFIG_DEFAULTS = {
    ORTHOGRAPHIC_FRUSTUM_TOP: ORTHOGRAPHIC_BASIS,
    ORTHOGRAPHIC_FRUSTUM_BOTTOM: -ORTHOGRAPHIC_BASIS,
    ORTHOGRAPHIC_FRUSTUM_LEFT: -ORTHOGRAPHIC_BASIS * window.innerWidth / window.innerHeight,
    ORTHOGRAPHIC_FRUSTUM_RIGHT: ORTHOGRAPHIC_BASIS * window.innerWidth / window.innerHeight,
    ORTHOGRAPHIC_FRUSTUM_NEAR: 0,
    ORTHOGRAPHIC_FRUSTUM_FAR: 100,
    PERSPECTIVE_ASPECT_RATIO: window.innerWidth / window.innerHeight,
    PERSPECTIVE_FOV: 70,
    PERSPECTIVE_FRUSTUM_FAR: 100,
    PERSPECTIVE_FRUSTUM_NEAR: 0.01,
    INITIAL_ORTHOGRAPHIC_POSITION: [ 0, 0, 0 ],
    INITIAL_ORTHOGRAPHIC_TARGET: [ 1, 0, 0 ],
    INITIAL_PERSPECTIVE_POSITION: [ 0, AVERAGE_HUMAN_HEIGHT, 0 ],
    INITIAL_PERSPECTIVE_TARGET: [ 1, AVERAGE_HUMAN_HEIGHT, 0 ],
}

export default CAMERAS_CONFIG_DEFAULTS
